import Layout from "@/components/layout";

export default function About() {
    return (
        // <Layout>
        //     <Head>
        //         <title>About Us</title>
        //         <meta name="description" content="Generated by create next app" />
        //         <meta name="viewport" content="width=device-width, initial-scale=1" />
        //         <link rel="icon" href="/favicon.ico" />
        //         <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"></link>
        //     </Head>
            
        // </Layout>
        <Layout>
        <h2 className="text-center mb-5 mt-5">Product Collection -about</h2>
        <div className="container">
        <div className="row">
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>

        </div>

        <div className="row mt-3">
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>
            <div className="col-3">
                <div class="card">
                    <img src="https://www.billboard.com/wp-content/uploads/2023/05/Jennie-Kim-2023-met-gala-billboard-1548.jpg?w=942&h=623&crop=1" class="card-img-top" alt="photo"/>

                    <div class="card-body">
                        <h5 class="card-title">BlackPink</h5>
                        <p class="card-text">BLINK (Hangul: 블링크) is the official fandom name for the South Korean pop group BLACKPINK.</p>
                        <a href="#" class="btn" style={{backgroundColor: "palevioletred", color: "white"}}>Keep Smiling</a>
                    </div>
                </div>
            </div>

        </div>
        
        </div>
        </Layout>
    )
}